# Generated by Django 5.2.6 on 2025-09-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Укажите имя', max_length=100, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Укажите фамилию', max_length=100, verbose_name='Фамилия:'),
        ),
    ]
