# Generated by Django 5.2.6 on 2025-09-21 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('purchase', 'Купленный продукт'), ('reorder', 'Повторная покупка'), ('preference', 'Предпочтение пользователя')], max_length=100)),
                ('source', models.CharField(choices=[('implicit', 'Неявные - извлечено из истории заказов'), ('explicit', 'Явные - задано пользователем')], default='implicit', max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('aisle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.aisle')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Взаимодействие пользователя',
                'verbose_name_plural': 'Взаимодействия пользователей',
                'indexes': [models.Index(fields=['user_id', 'product_id'], name='preferences_user_id_d6c317_idx'), models.Index(fields=['user_id', 'aisle_id'], name='preferences_user_id_994240_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.aisle')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Явное предпочтение',
                'verbose_name_plural': 'Явные предпочтения',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'product_id'), name='unique_user_product_pref'), models.UniqueConstraint(fields=('user_id', 'aisle_id'), name='unique_user_aisle_pref')],
            },
        ),
    ]
