# Generated by Django 5.2.6 on 2025-09-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_aisle_id', models.IntegerField(db_index=True, help_text='Введите ID ряда (корзины)', unique=True, verbose_name='ID ряда (корзины) в датасете:')),
                ('aisle', models.CharField(help_text='Введите название ряда (корзины)', max_length=150, unique=True, verbose_name='Название ряда (корзины):')),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
                'ordering': ['id', 'dataset_aisle_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_department_id', models.IntegerField(db_index=True, help_text='Введите ID департамента в датасете', unique=True, verbose_name='ID департамента в датасете:')),
                ('department', models.CharField(help_text='Введите название департамента', max_length=150, unique=True, verbose_name='Название департамента:')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'ordering': ['id', 'dataset_department_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_product_id', models.IntegerField(db_index=True, help_text='Введите ID продукта', unique=True, verbose_name='ID продукта в датасете:')),
                ('product_name', models.CharField(help_text='Введите название продукта', max_length=300, verbose_name='Название продукта:')),
                ('aisle_id', models.ForeignKey(help_text='Укажите ряд продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.aisle', verbose_name='Ряд продукта:')),
                ('department_id', models.ForeignKey(help_text='Укажите департамент продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.department', verbose_name='Департамент продукта:')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id', 'dataset_product_id'],
            },
        ),
    ]
