# Generated by Django 5.2.6 on 2025-09-20 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_order_id', models.IntegerField(db_index=True, help_text='Введите ID заказа', unique=True, verbose_name='ID заказа в датасете:')),
                ('order_number', models.PositiveIntegerField(help_text='Укажите номер заказа пользователя', verbose_name='Номер заказа пользователя:')),
                ('order_dow', models.IntegerField(help_text='Укажите день недели в заказе (0 = воскресенье, 1 = понедельник и т.д.)', verbose_name='День недели в заказе (0 = воскресенье, 1 = понедельник и т.д.):')),
                ('order_hour_of_day', models.IntegerField(help_text='Укажите час в заказе (например: 14 = 14:00)', verbose_name='Час в заказе (например: 14 = 14:00):')),
                ('days_since_prior_order', models.IntegerField(blank=True, help_text='Укажите сколько дней прошло с предыдущего заказа', null=True, verbose_name='Сколько дней прошло с предыдущего заказа:')),
                ('user_id', models.ForeignKey(help_text='Укажите владельца заказа', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец заказа:')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id', 'dataset_order_id', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_cart_order', models.PositiveSmallIntegerField(help_text='Укажите порядковый номер добавления товара в корзину', verbose_name='Порядковый номер добавления товара в корзину:')),
                ('reordered', models.PositiveSmallIntegerField(help_text='Укажите признак повторной покупки (1 - уже заказывался ранее, 0 - заказан впервые)', verbose_name='Признак повторной покупки (1 - уже заказывался ранее, 0 - заказан впервые):')),
                ('order_id', models.ForeignKey(help_text='Укажите ID заказа', on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order', verbose_name='ID заказа:')),
                ('product_id', models.ForeignKey(help_text='Укажите ID продуктов в заказе', on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='catalog.product', verbose_name='ID продуктов в заказе:')),
            ],
        ),
    ]
